version: "3.9"

services:
  database:
    image: conectasptech/mysql-image:latest
    container_name: mysql-db
    networks:
      - my-bridge
    volumes:
      - /opt:/var/lib/mysql

  application:
    image: conectasptech/java-image:latest
    container_name: java-app
    networks:
      - my-bridge
    depends_on:
      - database
    command: ["java","-jar","/app/java/jar-conecta-1.0-SNAPSHOT-jar-with-dependencies.jar"]

networks:
  my-bridge:
    driver: bridge
