version: "3.9"

services:
  database:
    image: conectasptech/mysql-image:latest
    container_name: mysql-db
    networks:
      - my-bridge

  application:
    image: conectasptech/java-image:latest
    container_name: java-app
    networks:
      - my-bridge
    depends_on:
      - database

networks:
  my-bridge:
    driver: bridge
